FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
        streamlit==1.40.0 \
        requests==2.32.5 \
        python-dotenv==1.0.1

COPY matchstream_frontend/app ./app

EXPOSE 8501

CMD ["streamlit", "run", "app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]