import os

WRITER_DB_HOST = os.getenv("WRITER_DB_HOST")
WRITER_DB_PORT = os.getenv("WRITER_DB_PORT")
WRITER_DB_NAME = os.getenv("POSTGRES_DB")
WRITER_DB_USER = os.getenv("POSTGRES_USER")
WRITER_DB_PASSWORD = os.getenv("POSTGRES_PASSWORD")
WRITER_DB_URL = os.getenv("WRITER_DB_URL")

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")
KAFKA_USERS_TOPIC = os.getenv("KAFKA_USERS_TOPIC")

KAFKA_GROUP_ID = "matchstream-users-db-writer"
BATCH_SIZE = 100