version: 2

models:

  - name: dim_states
    columns:
      - name: state_id
        tests: [unique, not_null]
      - name: state_name_id
      - name: state_name

  - name: dim_cities
    columns:
      - name: city_id
        tests: [unique, not_null]
      - name: city_name
      - name: state_id
        tests:
          - relationships:
              to: ref('dim_states')
              field: state_id

  - name: users
    columns:
      - name: user_id
        tests: [unique, not_null]
      - name: state_id
        tests:
          - relationships:
              to: ref('dim_states')
              field: state_id
      - name: city_id
        tests:
          - relationships:
              to: ref('dim_cities')
              field: city_id

  - name: users_contact
    columns:
      - name: user_id
        tests: [unique, not_null]

  - name: users_metadata
    columns:
      - name: user_id
        tests: [unique, not_null]

  - name: users_picture
    columns:
      - name: user_id
        tests: [unique, not_null]