version: 2

models:
  - name: dim_users
    description: "Denormalized dimension of users joined with contact, picture, metadata, and geo dimensions."

    columns:
      - name: user_id
        description: "Unique identifier for the user."
        tests:
          - not_null
          - unique

      - name: gender
        description: "User gender."

      - name: first_name
        description: "User first name."

      - name: last_name
        description: "User last name."

      - name: age
        description: "Calculated age based on date of birth."

      # Contact
      - name: phone
        description: "User phone number."

      - name: cell
        description: "User cell number."

      - name: email
        description: "User email address."

      # Pictures
      - name: picture_large
        description: "URL to large profile picture."

      - name: picture_medium
        description: "URL to medium profile picture."

      - name: picture_thumbnail
        description: "URL to thumbnail profile picture."

      # Geo
      - name: city_id
        description: "Foreign key to dim_cities."
        tests:
          - relationships:
              to: ref('dim_cities')
              field: city_id

      - name: city_name
        description: "City name from dim_cities."

      - name: state_id
        description: "Foreign key to dim_states."
        tests:
          - relationships:
              to: ref('dim_states')
              field: state_id

      - name: state_name
        description: "State name from dim_states."

      - name: state_name_id
        description: "State name identifier (two-letter code or similar)."

      - name: latitude
        description: "City latitude."

      - name: longitude
        description: "City longitude."

      # Metadata
      - name: created_at
        description: "User creation datetime."

      - name: ingested_at_bronze
        description: "Timestamp when the user CDC event was ingested from bronze."