FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    python3-dev \
    procps \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    kafka-python==2.2.2 \
    psycopg2-binary==2.9.9 \
    python-dotenv==1.0.1

COPY . .

CMD ["tail", "-f", "/dev/null"]