WRITER_DB_HOST = "pg_writer"
WRITER_DB_PORT = 5432
WRITER_DB_NAME = "matchstream"
WRITER_DB_USER = "writer_user"
WRITER_DB_PASSWORD = "writer_pass"

WRITER_DB_URL = (
    f"postgresql://{WRITER_DB_USER}:{WRITER_DB_PASSWORD}"
    f"@{WRITER_DB_HOST}:{WRITER_DB_PORT}/{WRITER_DB_NAME}"
)


KAFKA_BOOTSTRAP_SERVERS = "kafka_broker:9092"
KAFKA_USERS_TOPIC = "users"